### ISSUE TITLE
ffmpeg issues invalid argument error

### ISSUE THREAD

**Issue by ProConEmu** [transitive-bullshit/ffmpeg-concat#11]
After upgrading node.js to 8.11.2, running ffmpeg-cat is now running two ffmpeg commands and then dying on the third call with an invalid argument error.  I am seeing the same error running both on Linux Mint 17 and also on Windows 10.  The temp directories are different, but the errors are the same.  Here is the output from running on Linux:

ffmpeg-concat -t circleopen -d 1000 -o test.wmv /theVault/video/TOV.wmv /theVault/video/TOV2.wmv
{ cmd: 'ffmpeg -i /theVault/video/TOV.wmv -y -pix_fmt rgba -start_number 0 /tmp/3bf4f71398a2b4c30f4d3b29f758966d/scene-0-%012d.raw' }
{ cmd: 'ffmpeg -i /theVault/video/TOV2.wmv -y -pix_fmt rgba -start_number 0 /tmp/3bf4f71398a2b4c30f4d3b29f758966d/scene-1-%012d.raw' }
init-frames: 8067.804ms
render-frames: 3792.801ms
{ cmd: 'ffmpeg -framerate NaN -vcodec rawvideo -pixel_format rgba -video_size 320x240 -i /tmp/3bf4f71398a2b4c30f4d3b29f758966d/%012d.raw -y -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r NaN test.wmv' }
concat error Error: ffmpeg exited with code 1: /tmp/3bf4f71398a2b4c30f4d3b29f758966d/%012d.raw: Invalid argument

    at ChildProcess.<anonymous> (/home/gtaylor/.nvm/versions/node/v8.11.2/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
(node:3718) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: /tmp/3bf4f71398a2b4c30f4d3b29f758966d/%012d.raw: Invalid argument

**Comment by transitive-bullshit** [comment]
This is the problem `ffmpeg -framerate NaN`.

It's failing to calculate the correct framerate from your input videos.

If you can post your videos somewhere, I'll be able to inspect them and find the problem.

**Comment by mps-pune-consultant** [comment]
It is not working on mac. I have installed command line version using command "npm install -g ffmpeg-concat".

Below are the details - 
$ npm -version
6.1.0

$ node --version
v10.4.1

$ ffmpeg-concat -t fade -d 2000 -o final.mp4  output000.mp4 output001.mp4 
{ cmd:
   'ffmpeg -i output001.mp4 -y -pix_fmt rgba -start_number 0 /private/var/folders/d3/bl72wzrx2_x5pkk5whbv7hfh0000gn/T/05c93ea88e4cd0516b6ddece22f3542a/scene-1-%012d.raw' }
{ cmd:
   'ffmpeg -i output000.mp4 -y -pix_fmt rgba -start_number 0 /private/var/folders/d3/bl72wzrx2_x5pkk5whbv7hfh0000gn/T/05c93ea88e4cd0516b6ddece22f3542a/scene-0-%012d.raw' }
init-frames: 182.500ms
render 0%
render-frames: 43.159ms
{ cmd:
   'ffmpeg -framerate 0.2 -vcodec rawvideo -pixel_format rgba -video_size 720x406 -i /private/var/folders/d3/bl72wzrx2_x5pkk5whbv7hfh0000gn/T/05c93ea88e4cd0516b6ddece22f3542a/%012d.raw -y -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 0.2 final.mp4' }
transcode 30%
transcode-video: 170.710ms
ffmpeg-concat: 401.022ms
final.mp4

I have tried different transitions and none of it seems to work. Am I missing something?

**Comment by NCPatrick** [comment]
The issue is that the promise resolves while the files are still being written to the filesystem, so that when the app moves on to another filter/function, the mp4 file they process from is still being written.

I'm adding async/await to pause until the filesystem can catch up. I just didn't know if there was a flag or another way to tell when ffmpeg-concat was finished processing files besides just assuming resolve. 

I'm adding a check to make sure the files exist before resolving, otherwise I've had to resort to timeout/resolve, which is not ideal.

Thanks for the links!
