### ISSUE TITLE
Use ffmpeg-concat in Google Cloud Function?

### ISSUE THREAD

**Issue by becauseinterwebs** [transitive-bullshit/ffmpeg-concat#112]
Has anyone tried using ffmpeg-concat in a google cloud function?  It requires ffprobe to be installed and on path.  Is there a way to specify a path when calling the API?  I am using fluent-ffmpeg in a cloud function along with ffprobe-static and ffprobe.  With ffprobe you can specify the path:

`ffprobe(path, {path: ffprobeStatic.path});`

Is this possible in ffmpeg-concat? TIA!

**Comment by transitive-bullshit** [comment]
`ffprobe` may fit in a cloud function, but I doubt `ffmpeg` would. Not sure, though.

**Comment by silviuandrica** [comment]
Hi @becauseinterwebs ,

Did you manage to run ffmpeg-concat in a google cloud function? 

Im trying to do the same, but i get errors like 
```
Unhandled error Error: Unsupported input video format "mov,mp4,m4a,3gp,3g2,mj2": /tmp/yk7fitgqv5yjvdav2duf.mp4
    at AsyncFunction.module.exports.initScene (/workspace/node_modules/ffmpeg-concat/lib/init-frames.js:135:11)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) 
```

Cheers,
Silviu
