### ISSUE TITLE
Use image instead of video

### ISSUE THREAD

**Issue by ghprod** [transitive-bullshit/ffmpeg-concat#12]
Hi

Thanks for this package :+1: 

Instead of using video, can we use an image to create a video slideshow with this transition?

**Comment by transitive-bullshit** [comment]
This module only works with videos.

To create a video out of an image, see [here](https://stackoverflow.com/questions/25891342/creating-a-video-from-a-single-image-for-a-specific-duration-in-ffmpeg).

**Comment by transitive-bullshit** [comment]
Most likely, you'll want to create a kenburns-style zoom & pan effect from your image, which is beyond the scope of this package.

I have implemented this functionality for [Automagical](https://automagical.ai), and it may be open sourced in the future.

**Comment by ghprod** [comment]
@transitive-bullshit 

Thanks for your reply, btw your app (Automagical) really amazing!

Is that using ffmpeg?

**Comment by transitive-bullshit** [comment]
Yep :)
