### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by NCPatrick** [transitive-bullshit/ffmpeg-concat#13]
I switched from raw format to png and here jpg, but I'm getting the same error:

` ffmpeg-concat -f jpg -t circleopen -d 750 -o huzzah.mp4 condensed.mp4 SmallSampleVideo.mp4
(node:31972) ExperimentalWarning: The fs.promises API is experimental
{ cmd: 'ffmpeg -i SmallSampleVideo.mp4 -y -pix_fmt rgba -start_number 0 /private/var/folders/8v/78p3z4qj6tg78fs3z39220_m0000gn/T/d7ab0bc5d740fbd132ebddff4707cc49/scene-1-%012d.jpg' }
{ cmd: 'ffmpeg -i condensed.mp4 -y -pix_fmt rgba -start_number 0 /private/var/folders/8v/78p3z4qj6tg78fs3z39220_m0000gn/T/d7ab0bc5d740fbd132ebddff4707cc49/scene-0-%012d.jpg' }
init-frames: 3285.974ms
concat error { Error: ENOENT: no such file or directory, open '/private/var/folders/8v/78p3z4qj6tg78fs3z39220_m0000gn/T/d7ab0bc5d740fbd132ebddff4707cc49/scene-1-000000000NaN.jpg'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/private/var/folders/8v/78p3z4qj6tg78fs3z39220_m0000gn/T/d7ab0bc5d740fbd132ebddff4707cc49/scene-1-000000000NaN.jpg' }
(node:31972) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/private/var/folders/8v/78p3z4qj6tg78fs3z39220_m0000gn/T/d7ab0bc5d740fbd132ebddff4707cc49/scene-1-000000000NaN.jpg'
(node:31972) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31972) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
node -v  v10.1.0

**Comment by transitive-bullshit** [comment]
It looks like there was an error parsing the fps of the input videos. Can you post the input mp4's somewhere, and I'll track down the issue?

**Comment by NCPatrick** [comment]
Thanks. Here's my recent attempt:
` ffmpeg-concat -f jpg -t fade -d 500 -o output.mp4 condensed_one.mp4 condensed_two.mp4 
(node:35058) ExperimentalWarning: The fs.promises API is experimental
{ cmd: 'ffmpeg -i condensed_one.mp4 -y -pix_fmt rgba -start_number 0 /private/var/folders/8v/78p3z4qj6tg78fs3z39220_m0000gn/T/f72e07e49613e6faf7698f5a951b043e/scene-0-%012d.jpg' }
{ cmd: 'ffmpeg -i condensed_two.mp4 -y -pix_fmt rgba -start_number 0 /private/var/folders/8v/78p3z4qj6tg78fs3z39220_m0000gn/T/f72e07e49613e6faf7698f5a951b043e/scene-1-%012d.jpg' }
init-frames: 2629.277ms
render 0%
render 3%
render 7%
render 10%
render 13%
render 16%
render 20%
render 23%
render 26%
render 29%
render 33%
render 36%
render 39%
render 42%
render 46%
render 49%
render 52%
render 56%
render 59%
render 62%
render 65%
render 69%
render 72%
render 75%
render 78%
render 82%
render 85%
render 88%
render 91%
render 95%
render 98%
render-frames: 4658.664ms
{ cmd: 'ffmpeg -framerate 29.97 -i /private/var/folders/8v/78p3z4qj6tg78fs3z39220_m0000gn/T/f72e07e49613e6faf7698f5a951b043e/%012d.jpg -y -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 29.97 output.mp4' }
ffmpeg-concat: 7392.108ms`

I am getting this error: 
`concat error Error: ffmpeg exited with code 1: Unrecognized option 'preset'.
Error splitting the argument list: Option not found
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
(node:35058) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: Unrecognized option 'preset'.
Error splitting the argument list: Option not found
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
(node:35058) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35058) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
I am using fluent-ffmpeg@2.1.2. The option "preset" is not found.

**Comment by NCPatrick** [comment]
I have it now. I had to reinstall ffmpeg, ffmpeg-concat, and fluent-ffmpeg to get to the latest versions. Works great now. Thank you for the fix!
