### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by chenqingguo** [transitive-bullshit/ffmpeg-concat#131]
When applying diff
```
git apply ~/ffmpeg-gl-transition/ffmpeg.diff
```
I got this error
```
patch failed:libavfilter/allfilters.c:357
libavfilter/allfilters.c:path does not apply
```
Using Dockerfile to build docker also lead to the same error,
can anyone help?

**Comment by transitive-bullshit** [comment]
`ffmpeg-gl-transition` is a completely separate project.
