### ISSUE TITLE
issue with transitions not taking effect

### ISSUE THREAD

**Issue by mps-pune-consultant** [transitive-bullshit/ffmpeg-concat#14]
It is not working on mac. I have installed command line version using command "npm install -g ffmpeg-concat".

Below are the details -
$ npm -version
6.1.0

$ node --version
v10.4.1

$ ffmpeg-concat -t fade -d 2000 -o final.mp4 output000.mp4 output001.mp4
{ cmd:
'ffmpeg -i output001.mp4 -y -pix_fmt rgba -start_number 0 /private/var/folders/d3/bl72wzrx2_x5pkk5whbv7hfh0000gn/T/05c93ea88e4cd0516b6ddece22f3542a/scene-1-%012d.raw' }
{ cmd:
'ffmpeg -i output000.mp4 -y -pix_fmt rgba -start_number 0 /private/var/folders/d3/bl72wzrx2_x5pkk5whbv7hfh0000gn/T/05c93ea88e4cd0516b6ddece22f3542a/scene-0-%012d.raw' }
init-frames: 182.500ms
render 0%
render-frames: 43.159ms
{ cmd:
'ffmpeg -framerate 0.2 -vcodec rawvideo -pixel_format rgba -video_size 720x406 -i /private/var/folders/d3/bl72wzrx2_x5pkk5whbv7hfh0000gn/T/05c93ea88e4cd0516b6ddece22f3542a/%012d.raw -y -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 0.2 final.mp4' }
transcode 30%
transcode-video: 170.710ms
ffmpeg-concat: 401.022ms
final.mp4

When I play final.mp4, I don't see the transitions. I have tried different transitions and none of it seems to work. Am I missing something?

**Comment by transitive-bullshit** [comment]
It is working for many other people as well as myself, so it's likely there's a bug that may be specific to how your input videos are encoded.  Please upload them somewhere and I'll take a look.

**Comment by transitive-bullshit** [comment]
@mps-pune-consultant the videos you're using as input only have one frame each, and it's trying to apply the transition to that one frame.

You need to generate input videos with more normal fps (30 is pretty standard) to get the effect that you want. When you're creating your input videos, add the `fps` parameter as in this [thread](https://stackoverflow.com/questions/24961127/how-to-create-a-video-from-images-with-ffmpeg) and it'll work as intended.

**Comment by mps-pune-consultant** [comment]
It worked. Thanks a ton, appreciate the help.
