### ISSUE TITLE
Is there a way to pass transition parameters to gl-transition?

### ISSUE THREAD

**Issue by mirelon** [transitive-bullshit/ffmpeg-concat#15]
I want to use directional transition, but in horizontal way (default is vertical). I tried following options:
```
  {
    "name": "directional",
    "duration": 500,
    "direction": [1, 0],
    "paramsTypes":{"direction":"vec2"},
    "defaultParams":{"direction":[1,0]},
    "params":{"direction":[1,0]}
  }
```

But the resulting video contains the default vertical direction ([0,1])

**Comment by transitive-bullshit** [comment]
It's not currently supported, but it'd be fairly easy to add. Look at `lib/context.js` and `lib/transition.js`.  PRs welcome :)
