### ISSUE TITLE
What's the license?

### ISSUE THREAD

**Issue by crisdosaygo** [transitive-bullshit/ffmpeg-concat#156]
Hello, sorry for the probably rude sounding question but what's the license on this project?

**Comment by transitive-bullshit** [comment]
MIT :)

it's listed in the package.json, but I should prolly add a license file

**Comment by crisdosaygo** [comment]
Well, it makes it easier to see glancing at so it could be considered good documentation. At the same time, you're not alone in only throwing it in the package.json, I'm seeing that a lot!

Is it some kind of resist GitHub thing? 😆 🤷🏻
