### ISSUE TITLE
Debian Dependancies?

### ISSUE THREAD

**Issue by dustinb** [transitive-bullshit/ffmpeg-concat#2]
Installed on new Debian 9  (stretch) server.  Didn't like await, removed and got openGL error

```
const concat = require('ffmpeg-concat')

// concat 3 mp4s together using 2 500ms directionalWipe transitions
concat({
  output: 'test.mp4',
  videos: [
    'cut1.mp4',
    'cut22mp4'
  ],
  transition: {
    name: 'directionalWipe',
    duration: 500
  }
})
```

```
dustin@vultr:~/vrobot$ node index.js 
/home/dustin/vrobot/index.js:4
await concat({
^^^^^

SyntaxError: await is only valid in async function
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

dustin@vultr:~/vrobot$ vi index.js  (remove await)

dustin@vultr:~/vrobot$ node index.js 
{ cmd: 'ffmpeg -i cut1.mp4 -y -pix_fmt rgba -start_number 0 /tmp/4a1e082289b9aa5e6b06d0f4119a8131/scene-0-%012d.raw' }
{ cmd: 'ffmpeg -i cut2.mp4 -y -pix_fmt rgba -start_number 0 /tmp/4a1e082289b9aa5e6b06d0f4119a8131/scene-1-%012d.raw' }
init-frames: 33818.075ms
(node:6314) UnhandledPromiseRejectionWarning: Error: failed to create OpenGL context
    at module.exports (/home/dustin/vrobot/node_modules/ffmpeg-concat/lib/context.js:22:11)
    at module.exports (/home/dustin/vrobot/node_modules/ffmpeg-concat/lib/render-frames.js:19:21)
    at module.exports (/home/dustin/vrobot/node_modules/ffmpeg-concat/lib/index.js:44:30)
    at <anonymous>
(node:6314) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:6314) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by transitive-bullshit** [comment]
`concat` returns a Promise. You shouldn't use `async / await` if you're not familiar with how to use them.

It's likely you're running on a headless server, in which case you need to emulate a GPU (which is what OpenGL is all about).  See this [thread](https://github.com/transitive-bullshit/ffmpeg-gl-transition/issues/5) for help. Basically, you need to install and run mesa and xvfb.

**Comment by transitive-bullshit** [comment]
If you don't want to use `async / await` syntax, you can do the following instead:

```js
concat({
  output: 'test.mp4',
  videos: [
    'cut1.mp4',
    'cut22mp4'
  ],
  transition: {
    name: 'directionalWipe',
    duration: 500
  }
}).then(() => {
  console.log('done')
}, (err) => {
  console.error('error', err)
})
```

**Comment by dustinb** [comment]
Thanks for the help!   I don't think using a virtual gpu is practical.  I documented the steps I took here https://github.com/dustinb/vrobot to get a 6 CPU Debian server setup.   My test script has been running for 10 minutes.   Gonna look at the convoluted examples :) and/or some non OpenGL options.

**Comment by transitive-bullshit** [comment]
@dustinb Thanks for bringing this to my attention -- I ran your example, and it's definitely due to a bug in this library itself that's causing the renderer to deadlock.  Your xvfb setup looks fine.

I'm going to patch this bug now and I'll let you know once it's working on your example.

**Comment by dustinb** [comment]
Nice, confirmed about 30 seconds now.   I can open another issue after I test some more but it seems like the audio was lost after concat.

**Comment by transitive-bullshit** [comment]
Yeah, it's kind of undefined what the audio should be during the transition period, but I could change it to just fade between the input audio streams, if any.

**Comment by transitive-bullshit** [comment]
Audio transition progress tracked in #4
