### ISSUE TITLE
Video length of each clip is not preserved

### ISSUE THREAD

**Issue by mps-pune-consultant** [transitive-bullshit/ffmpeg-concat#20]
I have two video files 1.mp4 and 4.mp4 of duration 5 seconds each.
The files are uploaded at location - https://drive.google.com/drive/folders/1o3n-qLuvzSctzB5zXRfey_ViNScn8kwo?usp=sharing

**Case 1 :** 
Command - ffmpeg-concat -t 'Directional' -d 1000 -o final.mp4 1.mp4 4.mp4
I am getting video of duration 5 seconds instead of 10. The second video appears only for 1 second.

**Case 2 :**
Command - ffmpeg-concat -t 'Directional' -d 1000 -o final.mp4 4.mp4 1.mp4
Here I am getting video of duration 9 seconds instead of 10.

The questions are -

1. What is the error in the first case? The total length of the video should be 10 seconds.
2. How can we preserve the original length of the each video?

Thanks.

**Comment by transitive-bullshit** [comment]
The transition takes up time where both videos are being partially displayed. Therefore, the final video will not be the sum of the input video durations, but rather their sum *minus* the length of the transitions.

Your case 2 is correct timing-wise.  I'm guessing your case 1 videos have some weirdness to them.

Sorry, but I do not have the time to look into cases like these as this is an open source project that I'm contributing to in my spare time.

**Comment by rana01645** [comment]
> Thanks, appreciate the help.

@mps-pune-consultant  did you get any solution for case 1?? I'm facing the same issue
