### ISSUE TITLE
Duration of 700 ms not working 

### ISSUE THREAD

**Issue by mps-pune-consultant** [transitive-bullshit/ffmpeg-concat#21]
I am trying to apply transition on bunch of videos. When I use 1000 ms as transition duration, it succeeds. 
ffmpeg-concat -t 'Angular' -d 1000 -o final.mp4 1.mp4 2.mp4 3.mp4 4.mp4 5.mp4 6.mp4 7.mp4 8.mp4
ffmpeg-concat -t 'Fade' -d 1000 -o final.mp4 1.mp4 2.mp4 3.mp4 4.mp4 5.mp4 6.mp4 7.mp4 8.mp4

But when using 700 ms, it fails.
ffmpeg-concat -t 'Angular' -d 700 -o final.mp4 1.mp4 2.mp4 3.mp4 4.mp4 5.mp4 6.mp4 7.mp4 8.mp4
ffmpeg-concat -t 'Fade' -d 700 -o final.mp4 1.mp4 2.mp4 3.mp4 4.mp4 5.mp4 6.mp4 7.mp4 8.mp4

Error -
concat error Error: ffmpeg exited with code 69: Conversion failed!

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
(node:16531) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 69: Conversion failed!

    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
(node:16531) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16531) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

The videos are uploaded at location - https://drive.google.com/drive/folders/12jaWCvF7SzVHhnRAdGyRh1DPdOMhKKj9?usp=sharing

Thanks.

**Comment by mps-pune-consultant** [comment]
Anything less than 1000 ms is failing. I have tried 100, 500, 999 ms.

**Comment by transitive-bullshit** [comment]
Try upgrading the version of ffmeg-concat you're using. There was a bug that was recently fixed related to this.
