### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by NCPatrick** [transitive-bullshit/ffmpeg-concat#25]
I have everything working, running ffmpeg-concat as a promise. Everything is awesome. 

What is the best way to know when the processing has finished? Is there a check I can make, or is there a flag that gets thrown when processing is complete? 

At the moment I've got to set a timeout to a high number to make sure my processing completes so that I can resolve the promise and move the app logic forward.

Thanks very much!

**Comment by transitive-bullshit** [comment]
You can either run `ffmpeg-concat` as a CLI from the terminal or as a library from Node.js.

It looks like you're running it from Node.js, in which case you need to wait for the Promise to resolve. This is what Promises are all about 💯 They tell you exactly when asynchronous work finishes.

As such, you should definitely not be using timeouts to accomplish this. If you've never used Promises before, they're very powerful and relatively new to JavaScript.  I'd recommend that you read some tutorials to understand how to use them properly ([tutorial1](https://scotch.io/tutorials/javascript-promises-for-dummies) [tutorial2](https://www.promisejs.org/)).

Async & await are an even newer JavaScript features that make working with Promises easier, but I'd start with understanding Promises better first.

Good luck!
