### ISSUE TITLE
Create docker container for ffmpeg-concat?

### ISSUE THREAD

**Issue by jthomerson** [transitive-bullshit/ffmpeg-concat#27]
Would you consider making a docker container that has ffmpeg+node+ffmpeg-concat? This would make it super easy for people to test out ffmpeg-concat to see if it meets their needs without jumping through the tons of (sometimes very difficult) hoops of building it themselves.

Having containers like [jrottenberg/ffmpeg](https://hub.docker.com/r/jrottenberg/ffmpeg/) as a base may be helpful.

**Comment by transitive-bullshit** [comment]
Feel free to submit a PR 👍
