### ISSUE TITLE
Readme.md: Chinese translate {yes, me again}😊

### ISSUE THREAD

**Issue by chinanf-boy** [transitive-bullshit/ffmpeg-concat#28]
### 2. Or just this source repo Add a chinese repo link to

https://github.com/chinanf-boy/ffmpeg-concat-zh

## YOu choose `1` ?🌈

**Comment by transitive-bullshit** [comment]
Hey @chinanf-boy, please do #1 for all future requests, as this ensures that all documentation stays in one place.

Thanks!

**Comment by chinanf-boy** [comment]
THere

#29
