### ISSUE TITLE
"SyntaxError: Unexpected token" on Debian 9

### ISSUE THREAD

**Issue by bil80** [transitive-bullshit/ffmpeg-concat#3]
I installed it successfully on my Debian 9, and when i wanted to generate a video with transition effect with this command line: `ffmpeg-concat -t circleopen -d 750  0.mp4 1.mp4 -o output.mp4`

I got this error message:
`/usr/lib/node_modules/ffmpeg-concat/lib/index.js:12
module.exports = async (opts) => {
                       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/ffmpeg-concat/index.js:4:18)
`

have you an idea?

**Comment by transitive-bullshit** [comment]
What version of node are you using?

This module requires node >= 8.

**Comment by transitive-bullshit** [comment]
Make sure your system supports OpenGL.

If you're running on a headless server, you need to emulate a GPU (which is what OpenGL is all about).  See this [thread](https://github.com/transitive-bullshit/ffmpeg-gl-transition/issues/5) for help. Basically, you need to install and run mesa and xvfb.

**Comment by bil80** [comment]
I just installed mesa and xvfb successfully, i restarted the server, but i still have the same error: 
`Error: Could not locate the bindings file. Tried: → /usr/lib/node_modules/ffmpeg-concat/node_modules/gl/build/webgl.node .......`

I checked the folder /usr/lib/node_modules/ffmpeg-concat/node_modules/gl/ , i found that the directory "build" is missed, is it normal?

**Comment by bil80** [comment]
Ok il will check thank you.
