### ISSUE TITLE
Setup on an AWS t2 micro

### ISSUE THREAD

**Issue by chandramaulisingh** [transitive-bullshit/ffmpeg-concat#32]
Hi,

I am not able to get this running on a t2 micro running ubuntu. Seems to be an 'gl' issue. require('gl')(10,12) returns null.
Could you please share the setup steps for a headless linux machine.

Much appreciated

**Comment by transitive-bullshit** [comment]
Please search the existing issues before opening new issues. This has been answered multiple times on here previously.
