### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by ptsii** [transitive-bullshit/ffmpeg-concat#33]
after installing npm and trying to install ffmpeg-concat (on OSX 10.13.6) I run into all sorts of permission errors.  First, I get this:

$ npm install -g ffmpeg-concat
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/tom/.npm/_logs/2018-08-21T03_36_34_091Z-debug.log

Note that I was doing this as an administrator user, so...

When I try doing this:

sudo npm install -g ffmpeg-concat
/usr/local/bin/ffmpeg-concat -> /usr/local/lib/node_modules/ffmpeg-concat/index.js
+ ffmpeg-concat@1.0.11
updated 1 package in 15.069s

Looks like it works, right?  No:

$ ffmpeg-concat -v
/usr/local/lib/node_modules/ffmpeg-concat/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/build/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/build/Debug/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/build/Release/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/out/Debug/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/Debug/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/out/Release/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/Release/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/build/default/webgl.node
 → /usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/compiled/8.11.4/darwin/x64/webgl.node
    at bindings (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/webgl.js:4:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ffmpeg-concat/node_modules/gl/node_index.js:2:13)

Not sure what to try.

**Comment by transitive-bullshit** [comment]
This doesn't look like it has anything to do with this library in particular, but rather the global permissions for your node installation are messed up.

I would recommend installing `nvm` and a recent version node such as `8.11.0`, updating npm with `npm install -g npm`, before trying to install any global module, much less this one.

**Comment by ptsii** [comment]
I installed nvm with:

curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash

then:

$ sudo npm install -g npm
Password:
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
+ npm@6.4.0
added 278 packages, removed 363 packages and updated 41 packages in 7.378s

$ node -v
v8.11.4

However I get the same write permission errors as my first post when trying:

$ npm install -g ffmpeg-concat

If I do:

sudo npm install -g ffmpeg-concat
/usr/local/bin/ffmpeg-concat -> /usr/local/lib/node_modules/ffmpeg-concat/index.js
+ ffmpeg-concat@1.0.11
updated 1 package in 2.021s

But then, again:

$ ffmpeg-concat -v
/usr/local/lib/node_modules/ffmpeg-concat/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file.
[etc. as above]

ffmpeg-concat seems like a great solution, if only I could get it to install.

**Comment by transitive-bullshit** [comment]
You should never have to use `sudo` with `npm install`. If you do, then something is incorrectly configured on your system.

**Comment by ZhaoliangGuo** [comment]
how to install it in centos ?
