### ISSUE TITLE
-T transitions.json doesn't work correctly

### ISSUE THREAD

**Issue by Qriist** [transitive-bullshit/ffmpeg-concat#39]
First up, I am using Win10 x64. Via nvm, I am testing using Node 8.

I am attempting to use the -T option via CLI. I have a properly built json, syntax-wise. I know this because I edited it until concat's parser stopped yelling at me about tokens. However! No matter how I finagle the videos in the object or on the console I always get the error that the transitions must = n-1 videos.

I'm using the sample json shown on the front page, with a couple minor tweaks. (directory, quotes)
(Not wrapping in `code` because it collapsed it, which would probably be hard to read.)

{
  "output": "test.mp4",
  "videos": [
    "0.mp4",
    "1.mp4",
    "2.mp4",
    "0.mp4",
    "1.mp4"
  ],
  "transitions": [
    {
      "name": "circleOpen",
      "duration": 1000
    },
    {
      "name": "crossWarp",
      "duration": 800
    },
    {
      "name": "directionalWarp",
      "duration": 500,
      "params": { "direction": [ 1, -1 ] }
    },
    {
      "name": "squaresWire",
      "duration": 2000
    }
  ]
}

console output: https://i.imgur.com/uoRbxLi.png
Again, any combination of filenames on/off console or in/out the json produces this error with the -T option.

**Comment by albertok** [comment]
Working fine for me.

Does it still happen if the video file names are unique?

**Comment by transitive-bullshit** [comment]
@Qriist the json you provided is not for the `-T` option, but rather an example of how you would call the library programmatically from Node.js (as opposed to the CLI which you're trying to do).

Just take the `transitions` portion of that json snippet:

```json
[
  {
    "name": "circleOpen",
    "duration": 1000
  },
  {
    "name": "crossWarp",
    "duration": 800
  },
  {
    "name": "directionalWarp",
    "duration": 500,
    "params": {
      "direction": [
        1,
        -1
      ]
    }
  },
  {
    "name": "squaresWire",
    "duration": 2000
  }
]
```

Save this as a .json file and then pass 5 input videos via the CLI and it should work.

**Comment by Qriist** [comment]
I was able to get this to work. Incidentally, it does not work in tandem with the -f png option, but that is a minor quibble.
