### ISSUE TITLE
ffprobe PATH issues

### ISSUE THREAD

**Issue by Roost** [transitive-bullshit/ffmpeg-concat#41]
This package appears to fail if `ffprobe` is not stored in the `PATH`. Specifically, the `ffmpeg-probe` wrapper calls `ffprobe` directly even if the path has been specified to `fluent-ffmpeg`. 

A suggestion would be to allow settings the executable path explicitly as seen in `fluent-ffmpeg`, or to support setting an environment variable for the `ffprobe` path.

Details can be seen here: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg#ffmpeg-and-ffprobe

**Comment by transitive-bullshit** [comment]
Thanks for bringing this to my attention. I just released new versions of `ffmpeg-probe` and `ffmpeg-concat` which fix this issue as well as bumping all dependencies.

Thanks again!
