### ISSUE TITLE
Does not properly escape filenames

### ISSUE THREAD

**Issue by io12** [transitive-bullshit/ffmpeg-concat#43]
This tool fails with filenames with shell special characters like spaces, since it just concats the filenames to a shell command. You could probably fix this by using some exec() function to make the arguments explicit (I'm not that great at nodejs so I'm not sure which exact package/function is best).

**Comment by io12** [comment]
Oops looks like it's actually fine

**Comment by transitive-bullshit** [comment]
These are the best types of issues.. the types that fix themselves 😄
