### ISSUE TITLE
Error when trying to use the module

### ISSUE THREAD

**Issue by ayayy** [transitive-bullshit/ffmpeg-concat#45]
I am trying to type in my terminal `ffmpeg-concat -t circleopen -d 750 -o huzzah.mp4 1.mp4 2.mp4` but got this error

> node: symbol lookup error: ~/.nvm/versions/node/v11.0.0/lib/node_modules/ffmpeg-concat/node_modules/gl/build/Release/webgl.node: undefined symbol: _Z15XextFindDisplayP15_XExtensionInfoP9_XDisplay

How to solve it? 
I am using ubuntu

**Comment by transitive-bullshit** [comment]
This package uses OpenGL to apply the transitions which isn't available by default on all Linux machines or VMs without a display. You need to run additional software to emulate OpenGL.

See [here](https://github.com/stackgl/headless-gl#how-can-headless-gl-be-used-on-a-headless-linux-machine).

**Comment by ayayy** [comment]
Thx, example
`xvfb-run -s "-ac -screen 0 1280x1024x24" ffmpeg-concat -t circleopen -d 750 -o huzzah.mp4 1.mp4 2.mp4` 
worked for me

**Comment by ulisseslima** [comment]
This worked for me: 
`npm rebuild --build-from-source gl`
