### ISSUE TITLE
Can't predict how much time transition will cut out from input movies

### ISSUE THREAD

**Issue by mhmrx** [transitive-bullshit/ffmpeg-concat#52]
I need to know how much exacly each transition can cut of from each of movies. Currently - it is impossible.

**Comment by MitchellMonaghan** [comment]
I think this is literally the transition time.
videoDuration - transitionTime = newVideoDuration

**Comment by mhmrx** [comment]
It is. But you have to also remember to have the same fps for each of movies that you will concatenate. In other case it will be adjusted to the fps of first movie, and then overall time of whole movie can be different than expected.

**Comment by mhmrx** [comment]
Reason was diffrent FPS between input videos. ffmpeg-contact makes FPS the same for all videos as first input video.
