### ISSUE TITLE
Does ffmpeg-concat will be using GPU like ffmpeg-gl-transition?

### ISSUE THREAD

**Issue by javeedrahman** [transitive-bullshit/ffmpeg-concat#53]
Hi,

I would like to know whether the ffmpeg-concat will use my server GPU like https://github.com/transitive-bullshit/ffmpeg-gl-transition?

And i would like to know whether ffmpeg is using EGL or NON-EGL?

**Comment by transitive-bullshit** [comment]
ffmpeg-concat will use OpenGL and your GPU to render the transitions.

It's not quite as optimal as the ffmpeg-gl-transition approach.

ffmpeg-concat uses https://github.com/stackgl/headless-gl for OpenGL support. See their docs for more details.
