### ISSUE TITLE
windows installation issue 

### ISSUE THREAD

**Issue by raghuv9** [transitive-bullshit/ffmpeg-concat#54]
Unable to install ffmpeg-concat on windows
--------------------------------------------------------------------------------------------------------
Hey,i tried to install ffmpeg-concat as mentioned in the docs,before i tried this using latest versions of node and python i faced the same error, after going through the closed issues as suggested by author in one of those closed issues,i have uninstalled the latest node version and installed node-8 and python 2.7 , still i'm getting the following  errors from the past 2 days.
![Screenshot (6)](https://user-images.githubusercontent.com/26516842/68026301-553ff800-fcd5-11e9-83c9-a68f665363c6.png).

here are the steps i have followed to install ffmpeg-concat
-------------------------------------------------------
npm install --global --production windows-build-tools
npm install --global node-gyp
setx PYTHON "path\python27\python.exe"
npm install -g ffmpeg-concat.

**Comment by transitive-bullshit** [comment]
The error is coming from one of our dependencies, [headless-gl](https://github.com/stackgl/headless-gl).

Please post your issue over there. Most likely the "no pre-built binaries found" means that you should actually downgrade node.js to use a version which includes pre-built binaries for Windows. See that repo for details.

Thanks!

**Comment by raghuv9** [comment]
I already did that i downgraded my node from node 13 to node 8.1 version(suggested by you in a similar issue)still i'm getting the same error. i will post my issue in headless-gl repo ,thanks for the response Author.
