### ISSUE TITLE
Video concatenation time missmatch problem!

### ISSUE THREAD

**Issue by rana01645** [transitive-bullshit/ffmpeg-concat#57]
Thanks for the awesome library

But sometimes I get a time mismatch error like
 
video x is 5 second, video y is 10 second--- Total video output should be 15 seconds

but the output become only 8 seconds.

But when we concat with y to x instead of x,y we get the full 15 seconds as output.

Is there any solution for this error!

**Comment by Crispinli** [comment]
> Thanks for the awesome library
> 
> But sometimes I get a time mismatch error like
> 
> video x is 5 second, video y is 10 second--- Total video output should be 15 seconds
> 
> but the output become only 8 seconds.
> 
> But when we concat with y to x instead of x,y we get the full 15 seconds as output.
> 
> Is there any solution for this error!

I meet the same error, too. Did you solve it?

**Comment by rana01645** [comment]
@Crispinli  Yes.. all video ratio should be same for solving this problem

To convert ratio I used this ffmpeg command
ffmpeg -i input.mp4 -vf scale=1280:720 output.mp4 -y

**Comment by Crispinli** [comment]
> @Crispinli Yes.. all video ratio should be same for solving this problem
> 
> To convert ratio I used this ffmpeg command
> ffmpeg -i input.mp4 -vf scale=1280:720 output.mp4 -y

But my videos have same ratio...

**Comment by rana01645** [comment]
ffprobe -v error -show_entries stream=width,height -of csv=p=0:s=x video.mp4

Please run this command on both of your videos and double check they have same ratio.. If possible provide me your video link.. I will check this issue

**Comment by rana01645** [comment]
Or there might be audio duration issue... Please check your video has audio and that audio is equal to the video size...

check by this command
``ffprobe -v error -select_streams a:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 video.mp4``

If video ha no audio and the video and audio length is not equal you need to fill it with silent audio.

**Comment by Crispinli** [comment]
> `ffprobe -v error -show_entries stream=width,height -of csv=p=0:s=x video.mp4`
> 
> Please run this command on both of your videos and double check they have same ratio.. If possible provide me your video link.. I will check this issue

The ratio of two videos are same, 544x960. But the audio durations are different, 11.776000 and 11.716814. I will try to fix it.

**Comment by Crispinli** [comment]
> Or there might be audio duration issue... Please check your video has audio and that audio is equal to the video size...
> 
> check by this command
> `ffprobe -v error -select_streams a:0 -show_entries stream=duration -of default=noprint_wrappers=1:nokey=1 video.mp4`
> 
> If video ha no audio and the video and audio length is not equal you need to fill it with silent audio.

Another question, did you meet the issue "No audio output when using the CLI"? How did you solve it?
