### ISSUE TITLE
which loader is needed

### ISSUE THREAD

**Issue by gap1994** [transitive-bullshit/ffmpeg-concat#65]
I install it in Vue env, but it print this error.

 error  in ./node_modules/_ffmpeg-concat@1.0.14@ffmpeg-concat/index.js

Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders> #!/usr/bin/env node
| 'use strict'
|

**Comment by transitive-bullshit** [comment]
This is a Node.js module. It is not meant to be used with webpack -- webpack is meant for bundling scripts together for client-side usage.
