### ISSUE TITLE
Can this library be adapted to be used to combine a sequence of images instead of videos?

### ISSUE THREAD

**Issue by capezzbr** [transitive-bullshit/ffmpeg-concat#67]

**Comment by transitive-bullshit** [comment]
Create mp4s of the images first then use this library to concat those temp
videos.

**Comment by capezzbr** [comment]
Thanks @transitive-bullshit, sharing my solution here in case anybody else will ever need the same!

```javascript
await new Promise((resolve, reject) => {
    ffmpeg(image)
        .save(output)
        .outputOption('-pix_fmt yuv420p')
        .on('start', (command: string) => {
            Log.i(TAG, `ffmpeg process started: ${command}`)
        })
        .on('error', (error: string) => {
            reject(error)
        })
        .on('end', resolve)
})
```

**Comment by zhaishengfu** [comment]
hello. can you say more clearly? where should i add this code? thanks

**Comment by capezzbr** [comment]
@zhaishengfu that above snippet of code allows you to generate an mp4 video from an input image. You put that in a loop and you can generate an mp4 video for each one of your images then you can use `ffmpeg-concat` to concat them together

**Comment by zhaishengfu** [comment]
i am not familiar with node and npm, and I tried many methods to add your code
![image](https://user-images.githubusercontent.com/7630101/81142656-cae99100-8fa2-11ea-953f-981921e3a7c7.png)
the above code can run successfully . Thanks for your reply

**Comment by anonymousperson1209** [comment]
Hey. I'm hoping you can help me. I am now receiving this error when running your example:
```
UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: Error initializing output stream 0:0 -- 
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Conversion failed!
```
Any idea as to what I should do? Thanks in advance
