### ISSUE TITLE
Possible to use static FFMPEG ? 

### ISSUE THREAD

**Issue by SNRSE** [transitive-bullshit/ffmpeg-concat#73]
Hey,
i was wondering if its possible to use a static FFmpeg build ? 
where should I enter the path to the FFmpeg.exe ?

**Comment by transitive-bullshit** [comment]
Yes. We're using [fluent-ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg) under the hood. See their docs for how to override the FFMPEG PATH.
