### ISSUE TITLE
Unrecognized option 'preset'. Error splitting the argument list: Option not found

### ISSUE THREAD

**Issue by romualdo-ah** [transitive-bullshit/ffmpeg-concat#75]
I'm trying to concatenate some videos with the code below:
```javascript
 const concat = require('ffmpeg-concat')
 const glob = require('glob');
 const path = './videos/*.mp4'
 const videos = glob.sync(path);
 const output = `./output.mp4`;

async function start() {

await withFfmpegConcat()


async function withFfmpegConcat() {
 

     await concat({
       output,
       videos,
       transition: {
         name: 'directionalWipe',
         duration: 500
       }
     })
   }
}

 start()
```
And the console output some error message

**(node:3967) UnhandledPromiseRejectionWarning: Error: ffmpeg exited with code 1: Unrecognized option 'preset'.**
**Error splitting the argument list: Option not found**

   **at ChildProcess.<anonymous> (/home/r/Projects/webscrapping/node_modules/fluent-ffmpeg/lib/processor.js:182:22)**
    **at ChildProcess.emit (events.js:310:20)**

When it should concatenate these videos.

**Comment by transitive-bullshit** [comment]
What does `ffmpeg -version` output for you?

**Comment by romualdo-ah** [comment]
> What does `ffmpeg -version` output for you?
I was using version 4 and fixed it by reinstalling version 3 of ffmpeg, thank for the reply, and this package.
