### ISSUE TITLE
Output Video time mismatch problem

### ISSUE THREAD

**Issue by DanisHack** [transitive-bullshit/ffmpeg-concat#80]
Hi,

I am doing concatenation of 7 videos(with audio equal to video) and with similar dimensions. I get the output video with 3-4 secs less?

Can someone point out - what could be the potential issue?

**Comment by DanisHack** [comment]
@transitive-bullshit can you help here please

**Comment by transitive-bullshit** [comment]
It's almost certainly due to videos having different frame rates. `ffmpeg-concat` assumes that all input videos have the same frame rate.
