### ISSUE TITLE
[bug] CLI triggered when using native ESM modules

### ISSUE THREAD

**Issue by swlemp** [transitive-bullshit/ffmpeg-concat#82]
When I use `import concat from 'ffmpeg-concat';` the `ffprobe` CLI command is invoked without me actually calling it anywhere in the code.

Using latest macOS, latest ffmpeg-concat, node v12.16.2, using native ESM.

I get the error `concat error Error: Command failed: ffprobe -print_format json -show_error -show_format -show_streams $1` at the top of my script when I run it.

`$1` was passed to my script not to ffmpeg-concat which again was just imported in a JS file but not used anywhere.  The script thinks it's in CLI mode.

This is because the main script uses `module.parent` to check if we are in CLI mode, which I suppose does not fly with ESM.

**Comment by swlemp** [comment]
ping @transitive-bullshit

**Comment by transitive-bullshit** [comment]
Ahhh this is definitely a bug.

I've been using this `module.parent` trick for a long while -- guess I'll have to investigate the proper ESM way of doing things 😄

**Comment by transitive-bullshit** [comment]
Released as `v1.2.0`.
