### ISSUE TITLE
[feature] Add custom encode parameters ?

### ISSUE THREAD

**Issue by pythonsan** [transitive-bullshit/ffmpeg-concat#83]
The project uses fixed coding parameters by default:

`-c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart`

The above encoding parameters will make the encoding speed very fast, but the quality is not very good.

So, provide a custom input encoding parameter entry, such as **argv**, or **json**, can provide enough flexibility

Thank you :-)

**Comment by transitive-bullshit** [comment]
Would gladly accept a PR for this.

**Comment by transitive-bullshit** [comment]
Released as `v1.2.0`.
